JsonAssets/Mod.cs

Also fix one instance that was missing handling any combined ring checks at all.

Change Ring Fixing logic to recursive function

---

GenericModConfigMenu/Api.cs
GenericModConfigMenu/Framework/Api.cs
GenericModConfigMenu/Framework/SpecificModConfigMenu.cs
GenericModConfigMenu/IGenericModConfigMenuApi.cs

Changes:
* Extract API to its own file, so we can do away with that Gist, and have a reference to an always-up-to-date interface file
* Add `TryGetCurrentMenu` API method

[GMCM] API Improvements

---

CapstoneProfessions/i18n/zh.json

Add Chinese translations for Capstone Professions

---

Displays/Framework/Mannequin.cs
Displays/i18n/de.json
Displays/i18n/default.json
Displays/i18n/zh.json

This one is to improve the German translation. There isn't really a good word for plain. So I opted to remove the adjective altogether. Needed to change a bit of code though.

Make Displays translations more granular, improve German translations

---

JsonAssets/docs/author-guide.md

Added small clarification on which fields must go inside the recipe block

Added recipe block clarification

---

SurfingFestival/i18n/ko.json

Update Korean translations for Surfing Festival

---

MoreBuildings/i18n/ko.json

Add Korean translations for More Buildings

---

MoreRings/i18n/ko.json

Add Korean translations for More Rings

---

Magic/i18n/ko.json

Update Korean translations for Magic

---

BugNet/i18n/ko.json

Add Korean translations for Bug Net

---

CapstoneProfessions/i18n/ko.json

Add Korean translations for Capstone Professions

---

AnimalSocialMenu/i18n/fr.json
Displays/i18n/fr.json
JumpOver/i18n/fr.json
JunimosAcceptCash/i18n/fr.json
StatueOfGenerosity/i18n/fr.json

French translations for various mods.

Add French translations for Animal Social Menu, Displays, Jump Over, Junimos Accept Cash, and Statue of Generosity

---

RushOrders/i18n/ko.json

Add Korean translations for Rush Orders

---

GenericModConfigMenu/i18n/ko.json

Update Korean translations for Generic Mod Config Menu

---

HybridCropEngine/i18n/ko.json

Add Korean translations for Hybrid Crop Engine

---

AnotherHungerMod/i18n/ko.json

Add Korean translations for Another Hunger Mod

---

CombatLevelDamageScaler/i18n/ko.json

Add Korean translations for Combat Level Damage Scaler

---

CookingSkill/i18n/ko.json

Add Korean translations for Cooking Skill

---

Displays/i18n/ko.json

Add Korean translations for Displays

---

DynamicGameAssets/i18n/ko.json

Add Korean translations for Dynamic Game Assets

---

TheftOfTheWinterStar/i18n/ko.json

Add Korean translations for Theft of the Winter Star

---

StatueOfGenerosity/i18n/ko.json

Add Korean translations for Statue of Generosity

---

SleepyEye/i18n/ko.json

Add Korean translations for Sleepy Eye

---

RealtimeMinimap/i18n/ko.json

Add Korean translations for Realtime Minimap

---

PreexistingRelationship/i18n/ko.json

Add Korean translations for Preexisting Relationship

---

ObjectTimeLeft/i18n/ko.json

Add Korean translations for Object Time Left

---

MoreRings/i18n/ko.json

Update Korean translations for More Rings

---

LuckSkill/i18n/ko.json

Add Korean translations for Luck Skill

---

JunimosAcceptCash/i18n/ko.json

Add Korean translations for Junimos Accept Cash

---

뛰어 넘다/i18n/ko.json

Add Korean translations for Jump Over

---

FlowerRain/i18n/ko.json

Add Korean translations for Flower Rain

---

Magic/i18n/de.json

Add German translations for Magic

---

SpaceCore/i18n/de.json

Add German translations for SpaceCore

---

LuckSkill/i18n/de.json

Add German translations for Luck Skill

---

GenericModConfigMenu/i18n/de.json

Add German translations for Generic Mod Config Menu

---

CookingSkill/i18n/de.json

Add German translations for Cooking Skill
